In [1]:
# Import required libraries
import numpy as np
import tensorflow as tf

# Step 1: Create a small random dataset
np.random.seed(42)  # For reproducible results
input_data = np.random.rand(4, 5) * 10  # 4 samples, 5 features #(rows and column)

print("Original Input Values:\n")
print(input_data)

# Step 2: Apply Batch Normalization
batch_norm = tf.keras.layers.BatchNormalization() #keras → Deep Learning API ,,,,layers → Contains neural network layers

# training=True ensures batch statistics are used
batch_output = batch_norm(input_data, training=True)

print("\nBatch Normalization Output:\n")
print(batch_output.numpy())

# Step 3: Apply Layer Normalization
layer_norm = tf.keras.layers.LayerNormalization()

layer_output = layer_norm(input_data)

print("\nLayer Normalization Output:\n")
print(layer_output.numpy())

# Step 4: Short Comparison
print("\nComparison:")
print("--------------------------------------------")
print("1. Batch Normalization normalizes the input using the mean and variance of the entire batch.")
print("2. It helps stabilize and speed up the training of deep neural networks.")
print("3. Layer Normalization normalizes the features within each individual sample.")
print("4. It works independently of the batch size and is commonly used in RNNs and Transformers.")
print("5. Difference: Batch Normalization depends on batch statistics, whereas Layer Normalization depends only on the features of each sample.")
print("--------------------------------------------")

Original Input Values:

[[3.74540119 9.50714306 7.31993942 5.98658484 1.5601864 ]
 [1.5599452  0.58083612 8.66176146 6.01115012 7.08072578]
 [0.20584494 9.69909852 8.32442641 2.12339111 1.81824967]
 [1.8340451  3.04242243 5.24756432 4.31945019 2.9122914 ]]

Batch Normalization Output:

[[ 1.5112275   0.9517319  -0.05144119  0.8649404  -0.80403215]
 [-0.21876824 -1.2840501   0.95646095  0.8803768   1.6858699 ]
 [-1.290667    0.9998112   0.703074   -1.5626479  -0.6876391 ]
 [-0.00179219 -0.6674938  -1.608094   -0.18266845 -0.19419885]]

Layer Normalization Output:

[[-0.6801765   1.406119    0.61414444  0.13134396 -1.4714309 ]
 [-1.019102   -1.3290837   1.2293022   0.3901302   0.7287532 ]
 [-1.1072183   1.3786416   1.0186763  -0.60509837 -0.6850013 ]
 [-1.3780595  -0.36089128  1.4953172   0.7140644  -0.47043085]]

Comparison:
--------------------------------------------
1. Batch Normalization normalizes the input using the mean and variance of the entire batch.
2. It helps stabilize and 