In [ ]:
Batch Normalization and Layer Normalization 

In [2]:
import numpy as np

np.set_printoptions(precision=3, suppress=True)

x = np.array([
    [1.0, 2.0, 30.0],
    [2.0, 4.0, 32.0],
    [3.0, 8.0, 28.0],
    [4.0, 8.0, 34.0]
])

print("Input data:\n", x)

Input data:
 [[ 1.  2. 30.]
 [ 2.  4. 32.]
 [ 3.  8. 28.]
 [ 4.  8. 34.]]


In [4]:
eps = 1e-5

mean = x.mean(axis=0)    # mean of each column (feature), across the 4 rows
var = x.var(axis=0)      # variance of each column

print("mean per feature:", mean)
print("var per feature :", var)

x_hat = (x - mean) / np.sqrt(var + eps)

print("\nNormalized X (x_hat):\n", x_hat)
print("\nnew mean per feature (should be ~0):", x_hat.mean(axis=0))
print("new var per feature (should be ~1):", x_hat.var(axis=0))

mean per feature: [ 2.5  5.5 31. ]
var per feature : [1.25 6.75 5.  ]

Normalized X (x_hat):
 [[-1.342 -1.347 -0.447]
 [-0.447 -0.577  0.447]
 [ 0.447  0.962 -1.342]
 [ 1.342  0.962  1.342]]

new mean per feature (should be ~0): [0. 0. 0.]
new var per feature (should be ~1): [1. 1. 1.]


In [6]:
gamma = np.ones(3)
beta  = np.zeros(3)

out = gamma * x_hat + beta
print("output after gamma/beta:\n", out)

output after gamma/beta:
 [[-1.342 -1.347 -0.447]
 [-0.447 -0.577  0.447]
 [ 0.447  0.962 -1.342]
 [ 1.342  0.962  1.342]]


In [8]:
mean_ln = x.mean(axis=1, keepdims=True)    # mean of each ROW (sample), across its features
var_ln = x.var(axis=1, keepdims=True)

x_hat_ln = (x - mean_ln) / np.sqrt(var_ln + eps)

print("LayerNorm normalized X:\n", x_hat_ln)
print("\nrow means (should be ~0):", x_hat_ln.mean(axis=1))
print("row vars (should be ~1) :", x_hat_ln.var(axis=1))

LayerNorm normalized X:
 [[-0.744 -0.67   1.414]
 [-0.779 -0.633  1.412]
 [-0.926 -0.463  1.389]
 [-0.852 -0.551  1.404]]

row means (should be ~0): [ 0.  0.  0. -0.]
row vars (should be ~1) : [1. 1. 1. 1.]
